# ArgoCD,
# For this project:

# • Only use this GitHub repo
# • Only deploy into retail-store namespace
# • Only create these types of resources
# • Nothing else

# This YAML is the same thing you would configure in the ArgoCD UI under:
# Settings → Projects → New Project
# Instead of clicking in the UI, you are defining it as code (YAML).

# 🧠 Simple Explanation

# 👉 In UI → you configure project settings manually
# 👉 In YAML → you configure project settings using Git
# Both do the same thing.



apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: retail-store
  namespace: argocd
spec:
  description: Retail Store Sample Application
  
  sourceRepos:
    - 'https://github.com/LondheShubham153/retail-store-sample-app'
  
  destinations:
    - namespace: retail-store
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'cert-manager.io'
      kind: ClusterIssuer
  
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'policy'
      kind: PodDisruptionBudget 
